@baseUrl = http://localhost:6000
@adId = 67aec3bb9c6f39cd9af1e8ed

###
# GET ALL ADS
GET {{baseUrl}}/ads
Content-Type: application/json

###
# DELETE AN AD (SUBSTITUA {{adId}} PELO ID REAL)
DELETE {{baseUrl}}/ads/{{adId}}
Content-Type: application/json

###
# GET PRICE TREND FOR A SPECIFIC AD (SUBSTITUA {{adId}} PELO ID REAL)
GET {{baseUrl}}/price-trend/ads/{{adId}}/price-trend
Content-Type: application/json

###
# GET PRICE TRENDS FOR ALL ADS
GET {{baseUrl}}/price-trend/ads/price-trends
Content-Type: application/json

###
# GET PREDICTION FOR A SPECIFIC AD (SUBSTITUA {{adId}} PELO ID REAL)
GET {{baseUrl}}/predictions/ads/{{adId}}/prediction
Content-Type: application/json

###
# POST TEST NOTIFICATION
POST {{baseUrl}}/notifications/test
Content-Type: application/json

{
    "adId": "{{adId}}",
    "title": "Test Ad",
    "price": 2100,
    "url": "https://sp.olx.com.br/sao-paulo-e-regiao/informatica/placas-de-video/test"
}

###
# GET ALL NOTIFICATIONS
GET {{baseUrl}}/notifications
Content-Type: application/json
